version: "3.7"

services:
    # image project
    app:
        container_name: app_expense
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - hotel

    # nginx
    nginx:
        container_name: server_expense
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        depends_on:
            - app
        networks:
            - hotel

    # db postgres
    db:
        container_name: db_expense
        image: postgres:alpine
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=123456
            - POSTGRES_DB=default
            - POSTGRES_USER=default
        volumes:
            - ./.data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - hotel

networks:
    hotel:
        driver: bridge
